package com.jonasmp.ai.watcher;

import java.util.Arrays;
import java.util.HashSet;
import java.util.Set;
import org.bukkit.Location;
import org.bukkit.Material;
import org.bukkit.block.Block;

public final class WorldProtection {
   private static final double SPAWN_PROTECT_RADIUS = 100.0;
   private static final Set<Material> CONTAINERS = new HashSet<>(
      Arrays.asList(
         Material.CHEST,
         Material.TRAPPED_CHEST,
         Material.BARREL,
         Material.SHULKER_BOX,
         Material.WHITE_SHULKER_BOX,
         Material.ORANGE_SHULKER_BOX,
         Material.MAGENTA_SHULKER_BOX,
         Material.LIGHT_BLUE_SHULKER_BOX,
         Material.YELLOW_SHULKER_BOX,
         Material.LIME_SHULKER_BOX,
         Material.PINK_SHULKER_BOX,
         Material.GRAY_SHULKER_BOX,
         Material.LIGHT_GRAY_SHULKER_BOX,
         Material.CYAN_SHULKER_BOX,
         Material.PURPLE_SHULKER_BOX,
         Material.BLUE_SHULKER_BOX,
         Material.BROWN_SHULKER_BOX,
         Material.GREEN_SHULKER_BOX,
         Material.RED_SHULKER_BOX,
         Material.BLACK_SHULKER_BOX,
         Material.DISPENSER,
         Material.DROPPER,
         Material.HOPPER,
         Material.FURNACE,
         Material.BLAST_FURNACE,
         Material.SMOKER,
         Material.BREWING_STAND,
         Material.LECTERN,
         Material.COMPOSTER,
         Material.CHISELED_BOOKSHELF,
         Material.DECORATED_POT,
         Material.CRAFTER
      )
   );
   private static final Set<Material> DECORATIVE = new HashSet<>(
      Arrays.asList(
         Material.OAK_SIGN,
         Material.SPRUCE_SIGN,
         Material.BIRCH_SIGN,
         Material.JUNGLE_SIGN,
         Material.ACACIA_SIGN,
         Material.DARK_OAK_SIGN,
         Material.MANGROVE_SIGN,
         Material.CHERRY_SIGN,
         Material.BAMBOO_SIGN,
         Material.CRIMSON_SIGN,
         Material.WARPED_SIGN,
         Material.OAK_WALL_SIGN,
         Material.SPRUCE_WALL_SIGN,
         Material.BIRCH_WALL_SIGN,
         Material.JUNGLE_WALL_SIGN,
         Material.ACACIA_WALL_SIGN,
         Material.DARK_OAK_WALL_SIGN,
         Material.MANGROVE_WALL_SIGN,
         Material.CHERRY_WALL_SIGN,
         Material.BAMBOO_WALL_SIGN,
         Material.CRIMSON_WALL_SIGN,
         Material.WARPED_WALL_SIGN,
         Material.OAK_HANGING_SIGN,
         Material.SPRUCE_HANGING_SIGN,
         Material.BIRCH_HANGING_SIGN,
         Material.JUNGLE_HANGING_SIGN,
         Material.ACACIA_HANGING_SIGN,
         Material.DARK_OAK_HANGING_SIGN,
         Material.MANGROVE_HANGING_SIGN,
         Material.CHERRY_HANGING_SIGN,
         Material.BAMBOO_HANGING_SIGN,
         Material.CRIMSON_HANGING_SIGN,
         Material.WARPED_HANGING_SIGN,
         Material.ITEM_FRAME,
         Material.GLOW_ITEM_FRAME,
         Material.PAINTING,
         Material.FLOWER_POT,
         Material.POTTED_OAK_SAPLING,
         Material.POTTED_SPRUCE_SAPLING,
         Material.POTTED_BIRCH_SAPLING,
         Material.POTTED_JUNGLE_SAPLING,
         Material.POTTED_ACACIA_SAPLING,
         Material.POTTED_DARK_OAK_SAPLING,
         Material.POTTED_MANGROVE_PROPAGULE,
         Material.POTTED_CHERRY_SAPLING,
         Material.POTTED_BAMBOO,
         Material.POTTED_CACTUS,
         Material.POTTED_CORNFLOWER,
         Material.POTTED_LILY_OF_THE_VALLEY,
         Material.POTTED_WITHER_ROSE,
         Material.ARMOR_STAND,
         Material.END_CRYSTAL,
         Material.TORCH,
         Material.WALL_TORCH,
         Material.SOUL_TORCH,
         Material.SOUL_WALL_TORCH,
         Material.REDSTONE_TORCH,
         Material.REDSTONE_WALL_TORCH,
         Material.LANTERN,
         Material.SOUL_LANTERN,
         Material.SEA_LANTERN,
         Material.END_ROD,
         Material.GLOWSTONE,
         Material.SHROOMLIGHT,
         Material.CAMPFIRE,
         Material.SOUL_CAMPFIRE,
         Material.CANDLE,
         Material.WHITE_CANDLE,
         Material.ORANGE_CANDLE,
         Material.MAGENTA_CANDLE,
         Material.LIGHT_BLUE_CANDLE,
         Material.YELLOW_CANDLE,
         Material.LIME_CANDLE,
         Material.PINK_CANDLE,
         Material.GRAY_CANDLE,
         Material.LIGHT_GRAY_CANDLE,
         Material.CYAN_CANDLE,
         Material.PURPLE_CANDLE,
         Material.BLUE_CANDLE,
         Material.BROWN_CANDLE,
         Material.GREEN_CANDLE,
         Material.RED_CANDLE,
         Material.BLACK_CANDLE
      )
   );
   private static final Set<Material> NATURAL_BLOCKS = new HashSet<>(
      Arrays.asList(
         Material.STONE,
         Material.COBBLESTONE,
         Material.GRANITE,
         Material.DIORITE,
         Material.ANDESITE,
         Material.TUFF,
         Material.DEEPSLATE,
         Material.COBBLED_DEEPSLATE,
         Material.CALCITE,
         Material.DRIPSTONE_BLOCK,
         Material.POINTED_DRIPSTONE,
         Material.GRASS_BLOCK,
         Material.DIRT,
         Material.COARSE_DIRT,
         Material.PODZOL,
         Material.ROOTED_DIRT,
         Material.MUD,
         Material.SAND,
         Material.RED_SAND,
         Material.GRAVEL,
         Material.CLAY,
         Material.SNOW_BLOCK,
         Material.SNOW,
         Material.POWDER_SNOW,
         Material.ICE,
         Material.PACKED_ICE,
         Material.BLUE_ICE,
         Material.FROSTED_ICE,
         Material.OAK_LOG,
         Material.SPRUCE_LOG,
         Material.BIRCH_LOG,
         Material.JUNGLE_LOG,
         Material.ACACIA_LOG,
         Material.DARK_OAK_LOG,
         Material.MANGROVE_LOG,
         Material.CHERRY_LOG,
         Material.BAMBOO_BLOCK,
         Material.STRIPPED_OAK_LOG,
         Material.STRIPPED_SPRUCE_LOG,
         Material.STRIPPED_BIRCH_LOG,
         Material.STRIPPED_JUNGLE_LOG,
         Material.STRIPPED_ACACIA_LOG,
         Material.STRIPPED_DARK_OAK_LOG,
         Material.STRIPPED_MANGROVE_LOG,
         Material.STRIPPED_CHERRY_LOG,
         Material.OAK_LEAVES,
         Material.SPRUCE_LEAVES,
         Material.BIRCH_LEAVES,
         Material.JUNGLE_LEAVES,
         Material.ACACIA_LEAVES,
         Material.DARK_OAK_LEAVES,
         Material.MANGROVE_LEAVES,
         Material.CHERRY_LEAVES,
         Material.AZALEA_LEAVES,
         Material.FLOWERING_AZALEA_LEAVES,
         Material.OAK_PLANKS,
         Material.SPRUCE_PLANKS,
         Material.BIRCH_PLANKS,
         Material.JUNGLE_PLANKS,
         Material.ACACIA_PLANKS,
         Material.DARK_OAK_PLANKS,
         Material.MANGROVE_PLANKS,
         Material.CHERRY_PLANKS,
         Material.BAMBOO_PLANKS,
         Material.COAL_ORE,
         Material.IRON_ORE,
         Material.COPPER_ORE,
         Material.GOLD_ORE,
         Material.REDSTONE_ORE,
         Material.LAPIS_ORE,
         Material.DIAMOND_ORE,
         Material.EMERALD_ORE,
         Material.DEEPSLATE_COAL_ORE,
         Material.DEEPSLATE_IRON_ORE,
         Material.DEEPSLATE_COPPER_ORE,
         Material.DEEPSLATE_GOLD_ORE,
         Material.DEEPSLATE_REDSTONE_ORE,
         Material.DEEPSLATE_LAPIS_ORE,
         Material.DEEPSLATE_DIAMOND_ORE,
         Material.DEEPSLATE_EMERALD_ORE,
         Material.NETHER_GOLD_ORE,
         Material.NETHER_QUARTZ_ORE,
         Material.ANCIENT_DEBRIS,
         Material.OBSIDIAN,
         Material.BEDROCK,
         Material.NETHERRACK,
         Material.SOUL_SAND,
         Material.SOUL_SOIL,
         Material.BASALT,
         Material.SMOOTH_BASALT,
         Material.BLACKSTONE,
         Material.END_STONE,
         Material.PURPUR_BLOCK,
         Material.PURPUR_PILLAR,
         Material.TERRACOTTA,
         Material.WHITE_TERRACOTTA,
         Material.ORANGE_TERRACOTTA,
         Material.MAGENTA_TERRACOTTA,
         Material.LIGHT_BLUE_TERRACOTTA,
         Material.YELLOW_TERRACOTTA,
         Material.LIME_TERRACOTTA,
         Material.PINK_TERRACOTTA,
         Material.GRAY_TERRACOTTA,
         Material.LIGHT_GRAY_TERRACOTTA,
         Material.CYAN_TERRACOTTA,
         Material.PURPLE_TERRACOTTA,
         Material.BLUE_TERRACOTTA,
         Material.BROWN_TERRACOTTA,
         Material.GREEN_TERRACOTTA,
         Material.RED_TERRACOTTA,
         Material.BLACK_TERRACOTTA,
         Material.SANDSTONE,
         Material.RED_SANDSTONE,
         Material.CACTUS,
         Material.SUGAR_CANE,
         Material.KELP,
         Material.SEAGRASS,
         Material.TALL_SEAGRASS,
         Material.VINE,
         Material.CAVE_VINES,
         Material.CAVE_VINES_PLANT,
         Material.GLOW_LICHEN,
         Material.MOSS_BLOCK,
         Material.MOSS_CARPET,
         Material.AZALEA,
         Material.FLOWERING_AZALEA,
         Material.SPORE_BLOSSOM,
         Material.BIG_DRIPLEAF,
         Material.SMALL_DRIPLEAF,
         Material.SCULK,
         Material.SCULK_CATALYST,
         Material.SCULK_SHRIEKER,
         Material.SCULK_SENSOR,
         Material.SCULK_VEIN,
         Material.HAY_BLOCK,
         Material.PUMPKIN,
         Material.CARVED_PUMPKIN,
         Material.JACK_O_LANTERN,
         Material.MELON,
         Material.BROWN_MUSHROOM_BLOCK,
         Material.RED_MUSHROOM_BLOCK,
         Material.MUSHROOM_STEM,
         Material.CACTUS,
         Material.DEAD_BUSH,
         Material.FERN,
         Material.LARGE_FERN,
         Material.SHORT_GRASS,
         Material.TALL_GRASS,
         Material.SEAGRASS,
         Material.TALL_SEAGRASS,
         Material.DANDELION,
         Material.POPPY,
         Material.BLUE_ORCHID,
         Material.ALLIUM,
         Material.AZURE_BLUET,
         Material.RED_TULIP,
         Material.ORANGE_TULIP,
         Material.WHITE_TULIP,
         Material.PINK_TULIP,
         Material.OXEYE_DAISY,
         Material.CORNFLOWER,
         Material.LILY_OF_THE_VALLEY,
         Material.TORCHFLOWER,
         Material.SUNFLOWER,
         Material.LILAC,
         Material.ROSE_BUSH,
         Material.PEONY,
         Material.PITCHER_PLANT,
         Material.BROWN_MUSHROOM,
         Material.RED_MUSHROOM,
         Material.CRIMSON_FUNGUS,
         Material.WARPED_FUNGUS,
         Material.CRIMSON_ROOTS,
         Material.WARPED_ROOTS,
         Material.NETHER_SPROUTS,
         Material.TWISTING_VINES,
         Material.TWISTING_VINES_PLANT,
         Material.WEEPING_VINES,
         Material.WEEPING_VINES_PLANT,
         Material.BAMBOO,
         Material.BAMBOO_SAPLING,
         Material.SWEET_BERRY_BUSH,
         Material.CAVE_VINES,
         Material.HANGING_ROOTS,
         Material.BIG_DRIPLEAF_STEM
      )
   );

   private WorldProtection() {
   }

   public static boolean isProtected(Location loc) {
      if (loc != null && loc.getWorld() != null) {
         Location spawn = loc.getWorld().getSpawnLocation();
         return loc.distance(spawn) <= 100.0;
      } else {
         return false;
      }
   }

   public static boolean isContainer(Material type) {
      return type != null && CONTAINERS.contains(type);
   }

   public static boolean isDecorative(Material type) {
      return type != null && DECORATIVE.contains(type);
   }

   public static boolean isAllowedToBreak(Block block) {
      if (block == null) {
         return false;
      } else {
         Material type = block.getType();
         return !isContainer(type) && !isDecorative(type) ? NATURAL_BLOCKS.contains(type) : false;
      }
   }

   public static boolean isAllowedToPlace(Material type) {
      if (type == null) {
         return false;
      } else {
         return !isDecorative(type) && !isContainer(type) ? type.isBlock() && (type.isSolid() || NATURAL_BLOCKS.contains(type)) : false;
      }
   }
}
